on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: kenchan0130/actions-system-info@master
      id: system-info

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: v1-${{ runner.os }}-${{ steps.system-info.outputs.cpu-model }}-${{ hashFiles('**/Cargo.lock') }}

    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets --examples -- --deny=warnings

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: cargo doc
      uses: actions-rs/cargo@v1
      with:
        command: doc

    - name: cargo build --examples
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
